import 'package:flutter/material.dart';
import '../../data/models/column_info_model.dart';
import '../../data/models/database_metadata_model.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_text_field.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_number_field.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_date_picker.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_checkbox.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_readonly_field.dart';
import '../../presentation/widgets/foreign_key_dropdown.dart';
import '../../../../core/network/column_name_mapper.dart';
import 'field_type_mapper.dart';

class FormGeneratorService {
  Widget generateField({
    required ColumnInfoModel column,
    required DatabaseMetadataModel metadata,
    required String currentDatabase,
    dynamic initialValue,
    required Function(String, dynamic) onChanged,
  }) {
    print('🔨 generateField para columna: ${column.name}, initialValue: $initialValue');

    // 1. If it's PK with identity → Read-only field or hidden
    if (column.isIdentity) {
      if (initialValue != null) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: DynamicReadonlyField(
            label: column.name,
            value: initialValue.toString(),
          ),
        );
      }
      return const SizedBox.shrink(); // Hide in create mode
    }

    // 2. If it's auto-generated field (timestamps) → Hidden in create mode, read-only in edit
    final autoGeneratedFields = [
      'created_at',
      'updated_at',
      'deleted_at',
      'createdat',
      'updatedat',
      'deletedat',
    ];

    if (autoGeneratedFields.contains(column.name.toLowerCase())) {
      if (initialValue != null) {
        // Show as read-only in edit mode
        return Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: DynamicReadonlyField(
            label: column.name,
            value: initialValue.toString(),
          ),
        );
      }
      return const SizedBox.shrink(); // Hide in create mode
    }

    // 3. Hide usuario_id field completely (will be auto-populated)
    if (column.name.toLowerCase() == 'usuario_id') {
      // Always hide this field, it will be added automatically
      return const SizedBox.shrink();
    }

    // 4. If it's FK → Dropdown with data from referenced table
    final fk = metadata.getForeignKeyForColumn(column.table, column.name);

    if (fk != null) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: ForeignKeyDropdown(
          label: column.name,
          databaseName: currentDatabase,
          referenceTable: fk.referenceTable,
          referenceColumn: fk.referenceColumn,
          isRequired: !column.nullable,
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    // 3. According to data type → Corresponding widget
    final type = column.type.toLowerCase();

    if (FieldTypeMapper.isStringType(type) || FieldTypeMapper.isTextType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicTextField(
          label: column.name,
          maxLength: column.maxLength,
          isRequired: !column.nullable,
          initialValue: initialValue?.toString(),
          onChanged: (value) => onChanged(column.name, value),
          multiline: FieldTypeMapper.isTextType(type),
        ),
      );
    }

    if (FieldTypeMapper.isIntegerType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicNumberField(
          label: column.name,
          allowDecimal: false,
          isRequired: !column.nullable,
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isDecimalType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicNumberField(
          label: column.name,
          allowDecimal: true,
          isRequired: !column.nullable,
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isDateTimeType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicDatePicker(
          label: column.name,
          includeTime: type.contains('time') && type != 'time',
          isRequired: !column.nullable,
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isBooleanType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicCheckbox(
          label: column.name,
          initialValue: initialValue ?? false,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    // Default to text field
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: DynamicTextField(
        label: column.name,
        isRequired: !column.nullable,
        initialValue: initialValue?.toString(),
        onChanged: (value) => onChanged(column.name, value),
      ),
    );
  }

  /// Busca el valor inicial de una columna de forma flexible
  /// Intenta con el nombre exacto, snake_case, camelCase, PascalCase, y usa el mapper de columnas
  dynamic _getInitialValue(
    Map<String, dynamic>? initialData,
    String columnName,
    String tableName,
  ) {
    if (initialData == null || initialData.isEmpty) return null;

    print('🔎 Buscando initialValue para columna: "$columnName"');
    print('   📋 Keys disponibles: ${initialData.keys.toList()}');

    // Intento 1: Buscar por nombre exacto
    if (initialData.containsKey(columnName)) {
      print('   ✅ Encontrado (exacto): ${initialData[columnName]}');
      return initialData[columnName];
    }

    // Intento 2: Usar el mapper para obtener el nombre que usa el backend
    final backendName = ColumnNameMapper.getBackendName(tableName, columnName);
    if (backendName != columnName && initialData.containsKey(backendName)) {
      print('   ✅ Encontrado (mapper "$backendName"): ${initialData[backendName]}');
      return initialData[backendName];
    }

    // Intento 3: Convertir a PascalCase y buscar (más común del backend .NET)
    final pascalCaseName = _toPascalCase(columnName);
    if (initialData.containsKey(pascalCaseName)) {
      print('   ✅ Encontrado (PascalCase "$pascalCaseName"): ${initialData[pascalCaseName]}');
      return initialData[pascalCaseName];
    }

    // Intento 4: Convertir a camelCase y buscar
    final camelCaseName = _toCamelCase(columnName);
    if (initialData.containsKey(camelCaseName)) {
      print('   ✅ Encontrado (camelCase "$camelCaseName"): ${initialData[camelCaseName]}');
      return initialData[camelCaseName];
    }

    // Intento 5: Buscar en todas las keys ignorando case
    final lowerColumnName = columnName.toLowerCase();
    for (var entry in initialData.entries) {
      if (entry.key.toLowerCase() == lowerColumnName) {
        print('   ✅ Encontrado (case-insensitive "${entry.key}"): ${entry.value}');
        return entry.value;
      }
    }

    // Intento 6: Convertir a snake_case y buscar
    final snakeCaseName = _toSnakeCase(columnName);
    if (snakeCaseName != columnName && initialData.containsKey(snakeCaseName)) {
      print('   ✅ Encontrado (snake_case "$snakeCaseName"): ${initialData[snakeCaseName]}');
      return initialData[snakeCaseName];
    }

    print('   ❌ NO encontrado para columna "$columnName"');
    return null;
  }

  List<Widget> generateForm({
    required String tableName,
    required DatabaseMetadataModel metadata,
    required String currentDatabase,
    Map<String, dynamic>? initialData,
    required Function(String, dynamic) onFieldChanged,
  }) {
    final columns = metadata.getColumnsForTable(tableName);

    return columns.map((column) {
      final initialValue = _getInitialValue(initialData, column.name, tableName);

      return generateField(
        column: column,
        metadata: metadata,
        currentDatabase: currentDatabase,
        initialValue: initialValue,
        onChanged: onFieldChanged,
      );
    }).toList();
  }

  /// Convierte camelCase a snake_case
  String _toSnakeCase(String str) {
    return str.replaceAllMapped(
      RegExp(r'[A-Z]'),
      (match) => '_${match.group(0)!.toLowerCase()}',
    );
  }

  /// Convierte snake_case a camelCase
  String _toCamelCase(String str) {
    return str.replaceAllMapped(
      RegExp(r'_([a-z])'),
      (match) => match.group(1)!.toUpperCase(),
    );
  }

  /// Convierte snake_case a PascalCase (primera letra mayúscula)
  String _toPascalCase(String str) {
    // Primero convertir a camelCase
    final camel = _toCamelCase(str);
    // Luego capitalizar la primera letra
    if (camel.isEmpty) return camel;
    return camel[0].toUpperCase() + camel.substring(1);
  }

  /// Convierte snake_case al formato esperado por el backend .NET
  /// El backend espera PascalCase SIN underscores para mapear a las propiedades de C#
  /// Ej: profesor_id -> ProfesorId, codigo -> Codigo
  String _toBackendCase(String str) {
    // Usar la función existente _toPascalCase que ya hace la conversión correcta
    return _toPascalCase(str);
  }

  Map<String, dynamic> prepareDataForSubmit({
    required Map<String, dynamic> formData,
    required List<ColumnInfoModel> columns,
    int? currentUserId,
  }) {
    final Map<String, dynamic> preparedData = {};

    print('🔍 Preparando datos para enviar:');
    print('📦 formData keys: ${formData.keys.toList()}');
    print('📋 Available columns: ${columns.map((c) => c.name).toList()}');
    print('👤 Current user ID: $currentUserId');

    for (var entry in formData.entries) {
      print('🔎 Buscando columna para key: "${entry.key}"');

      // Buscar columna de forma flexible (soporta tanto snake_case como camelCase)
      ColumnInfoModel? column;

      // Intento 1: Buscar por nombre exacto
      column = columns.where((col) => col.name == entry.key).firstOrNull;

      // Intento 2: Convertir a snake_case y buscar
      if (column == null) {
        final snakeKey = _toSnakeCase(entry.key);
        column = columns.where((col) => col.name == snakeKey).firstOrNull;
        print('   🔄 Intentando con snake_case: "$snakeKey"');
      }

      // Intento 3: Convertir a camelCase y buscar
      if (column == null) {
        final camelKey = _toCamelCase(entry.key);
        column = columns.where((col) => col.name == camelKey).firstOrNull;
        print('   🔄 Intentando con camelCase: "$camelKey"');
      }

      if (column == null) {
        print('   ⚠️ Columna no encontrada, omitiendo campo "${entry.key}"');
        continue; // Omitir campos que no existen en lugar de lanzar error
      }

      print('   ✅ Columna encontrada: ${column.name}');

      // Skip identity columns (como 'id')
      if (column.isIdentity) {
        print('   ⏭️  Omitiendo columna identity: ${column.name}');
        continue;
      }

      // Skip campos auto-generados comunes (timestamps, etc.)
      final autoGeneratedFields = [
        'created_at',
        'updated_at',
        'deleted_at',
        'createdat',
        'updatedat',
        'deletedat',
      ];

      if (autoGeneratedFields.contains(column.name.toLowerCase())) {
        print('   ⏭️  Omitiendo campo auto-generado: ${column.name}');
        continue;
      }

      // Parse value according to type
      final parsedValue = FieldTypeMapper.parseValue(
        column.type,
        entry.value,
      );

      // Convertir el nombre de la columna para el backend .NET con Dapper
      // Dapper mapea directamente los nombres de columnas de la DB (snake_case)
      // Pero si usamos snake_case con primera letra mayúscula funciona mejor
      // Ej: profesor_id -> Profesor_Id (mantiene el underscore)
      final backendName = _toBackendCase(column.name);
      preparedData[backendName] = parsedValue;

      print('   📤 Agregando: $backendName = $parsedValue');
    }

    // IMPORTANTE: Si hay una columna usuario_id que no está en formData,
    // agregarla automáticamente con el ID del usuario logueado (sea nullable o no)
    final usuarioIdColumn = columns.where((col) =>
      col.name.toLowerCase() == 'usuario_id' && !col.isIdentity
    ).firstOrNull;

    if (usuarioIdColumn != null && currentUserId != null) {
      // Verificar si ya está en formData o en preparedData
      final hasUsuarioId = formData.keys.any((key) =>
        key.toLowerCase() == 'usuario_id' ||
        _toSnakeCase(key).toLowerCase() == 'usuario_id'
      ) || preparedData.containsKey('Usuario_Id') || preparedData.containsKey('UsuarioId');

      if (!hasUsuarioId) {
        print('🔐 Auto-agregando UsuarioId del usuario logueado: $currentUserId');
        // Usar el mismo formato que el resto de los campos (PascalCase)
        preparedData['UsuarioId'] = currentUserId;
      }
    }

    print('✅ Datos preparados (Backend format): $preparedData');
    return preparedData;
  }
}
