import 'package:flutter/material.dart';
import '../../data/models/column_info_model.dart';
import '../../data/models/database_metadata_model.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_text_field.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_number_field.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_date_picker.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_checkbox.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_readonly_field.dart';
import '../../presentation/widgets/foreign_key_dropdown.dart';
import '../../../../core/network/column_name_mapper.dart';
import 'field_type_mapper.dart';

class FormGeneratorService {
  Widget generateField({
    required ColumnInfoModel column,
    required DatabaseMetadataModel metadata,
    required String currentDatabase,
    dynamic initialValue,
    required Function(String, dynamic) onChanged,
  }) {
    // print('🔨 generateField para columna: ${column.name}, initialValue: $initialValue');

    // 1. Identity / PK
    if (column.isIdentity) {
      if (initialValue != null) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: DynamicReadonlyField(
            label: column.name,
            value: initialValue.toString(),
          ),
        );
      }
      return const SizedBox.shrink();
    }

    // 2. Auto-generated fields
    final autoGeneratedFields = [
      'created_at', 'updated_at', 'deleted_at',
      'createdat', 'updatedat', 'deletedat',
    ];

    if (autoGeneratedFields.contains(column.name.toLowerCase())) {
      if (initialValue != null) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: DynamicReadonlyField(
            label: column.name,
            value: initialValue.toString(),
          ),
        );
      }
      return const SizedBox.shrink(); 
    }

    // 3. Hide usuario_id
    if (column.name.toLowerCase() == 'usuario_id') {
      return const SizedBox.shrink();
    }

    // 4. FK Dropdown
    final fk = metadata.getForeignKeyForColumn(column.table, column.name);

    if (fk != null) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: ForeignKeyDropdown(
          label: column.name,
          databaseName: currentDatabase,
          referenceTable: fk.referenceTable,
          referenceColumn: fk.referenceColumn,
          isRequired: !column.nullable,
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    // 5. Data Types logic
    final type = column.type.toLowerCase();

    if (FieldTypeMapper.isStringType(type) || FieldTypeMapper.isTextType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicTextField(
          label: column.name,
          maxLength: column.maxLength,
          isRequired: !column.nullable,
          initialValue: initialValue?.toString(),
          onChanged: (value) => onChanged(column.name, value),
          multiline: FieldTypeMapper.isTextType(type),
        ),
      );
    }

    if (FieldTypeMapper.isIntegerType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicNumberField(
          label: column.name,
          allowDecimal: false,
          isRequired: !column.nullable,
          initialValue: initialValue?.toString(), // ✅ Importante: toString()
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isDecimalType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicNumberField(
          label: column.name,
          allowDecimal: true,
          isRequired: !column.nullable,
          initialValue: initialValue?.toString(), // ✅ Importante: toString()
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isDateTimeType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicDatePicker(
          label: column.name,
          includeTime: type.contains('time') && type != 'time',
          isRequired: !column.nullable,
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isBooleanType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicCheckbox(
          label: column.name,
          initialValue: initialValue ?? false,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    // Default
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: DynamicTextField(
        label: column.name,
        isRequired: !column.nullable,
        initialValue: initialValue?.toString(),
        onChanged: (value) => onChanged(column.name, value),
      ),
    );
  }

  /// BUSCADOR INTELIGENTE DE VALORES
  dynamic _getInitialValue(
    Map<String, dynamic>? initialData,
    String columnName,
    String tableName,
  ) {
    if (initialData == null || initialData.isEmpty) return null;

    // --- ZONA DE PARCHES (Casos Especiales) ---

    // 1. Estudiantes (Legajo -> Cedula)
    if (columnName.toLowerCase() == 'legajo') {
      if (initialData.containsKey('Cedula')) return initialData['Cedula'];
      if (initialData.containsKey('cedula')) return initialData['cedula'];
    }

    // 2. Búsqueda Fuzzy (Ignora mayúsculas y guiones bajos)
    // Resuelve: fecha_inscripcion vs FechaInscripcion
    final cleanColumnName = columnName.replaceAll('_', '').toLowerCase();
    
    for (var key in initialData.keys) {
      final cleanKey = key.replaceAll('_', '').toLowerCase();
      if (cleanKey == cleanColumnName) {
        return initialData[key];
      }
    }
    // --- FIN ZONA DE PARCHES ---

    // Búsquedas Estándar
    if (initialData.containsKey(columnName)) return initialData[columnName];

    final backendName = ColumnNameMapper.getBackendName(tableName, columnName);
    if (backendName != columnName && initialData.containsKey(backendName)) return initialData[backendName];

    final pascalCaseName = _toPascalCase(columnName);
    if (initialData.containsKey(pascalCaseName)) return initialData[pascalCaseName];

    final camelCaseName = _toCamelCase(columnName);
    if (initialData.containsKey(camelCaseName)) return initialData[camelCaseName];

    final lowerColumnName = columnName.toLowerCase();
    for (var entry in initialData.entries) {
      if (entry.key.toLowerCase() == lowerColumnName) return entry.value;
    }

    final snakeCaseName = _toSnakeCase(columnName);
    if (snakeCaseName != columnName && initialData.containsKey(snakeCaseName)) return initialData[snakeCaseName];

    return null;
  }

  List<Widget> generateForm({
    required String tableName,
    required DatabaseMetadataModel metadata,
    required String currentDatabase,
    Map<String, dynamic>? initialData,
    required Function(String, dynamic) onFieldChanged,
  }) {
    final columns = metadata.getColumnsForTable(tableName);

    return columns.map((column) {
      final initialValue = _getInitialValue(initialData, column.name, tableName);

      return generateField(
        column: column,
        metadata: metadata,
        currentDatabase: currentDatabase,
        initialValue: initialValue,
        onChanged: onFieldChanged,
      );
    }).toList();
  }

  String _toSnakeCase(String str) {
    return str.replaceAllMapped(
      RegExp(r'[A-Z]'),
      (match) => '_${match.group(0)!.toLowerCase()}',
    );
  }

  String _toCamelCase(String str) {
    return str.replaceAllMapped(
      RegExp(r'_([a-z])'),
      (match) => match.group(1)!.toUpperCase(),
    );
  }

  String _toPascalCase(String str) {
    final camel = _toCamelCase(str);
    if (camel.isEmpty) return camel;
    return camel[0].toUpperCase() + camel.substring(1);
  }

/// TRADUCTOR PARA ESCRITURA (Hacia el Backend)
  String _toBackendCase(String str) {
    final String lowerStr = str.toLowerCase();

    // CASO 1: Estudiantes
    if (lowerStr == 'legajo') return 'Cedula';
    
    // CASO 2: Calificación
    if (lowerStr == 'calificacion') return 'calificacion';

    // CASO 3, 5 y 8: Campos que requieren PascalCase CON Guion Bajo
    // 🚨 NOTA: He quitado nombre_empresa, contacto_nombre y sitio_web de aquí
    // porque tu clase Proveedor en C# NO usa guiones bajos.
    final columnasConGuionBajo = [
      'estudiante_id', 'curso_id', 'fecha_inscripcion', // Académico
      'cita_id', 'descripcion_diagnostico', 'tratamiento_recetado', 'proxima_visita', // Salud
      'producto_id', 'stock_actual', 'stock_minimo', 'ubicacion_almacen', // Inventario
      'padre_id', // Categorías
      'precio_costo', 'precio_venta', 'categoria_id', 'proveedor_id' // Productos
    ];

    if (columnasConGuionBajo.contains(lowerStr)) {
      // Convierte: stock_actual -> Stock_Actual
      return str.split('_').map((part) {
        if (part.isEmpty) return '';
        return part[0].toUpperCase() + part.substring(1);
      }).join('_');
    }

    // CASO 4: Salud - Citas (Minúsculas estrictas)
    final columnasSalud = ['paciente_id', 'medico_id', 'fecha_hora', 'motivo_consulta'];
    if (columnasSalud.contains(lowerStr)) {
      return lowerStr;
    }

    // CASO 6: PACIENTES (PascalCase sin guion bajo)
    final columnasPacientes = {
      'fecha_nacimiento': 'FechaNacimiento',
      'grupo_sanguineo': 'GrupoSanguineo',
    };

    if (columnasPacientes.containsKey(lowerStr)) {
      return columnasPacientes[lowerStr]!;
    }

    // Regla General: Convierte snake_case a PascalCase simple (ej: nombre_empresa -> NombreEmpresa)
    // Esto es lo que necesita tu clase Proveedor.
    return _toPascalCase(str);
  }

Map<String, dynamic> prepareDataForSubmit({
    required Map<String, dynamic> formData,
    required List<ColumnInfoModel> columns,
    int? currentUserId,
  }) {
    final Map<String, dynamic> preparedData = {};

    print('🔍 Preparando datos para enviar:');
    
    for (var entry in formData.entries) {
      // 1. Buscar la columna correspondiente en los metadatos
      ColumnInfoModel? column = columns.where((col) => col.name == entry.key).firstOrNull;

      if (column == null) {
        final snakeKey = _toSnakeCase(entry.key);
        column = columns.where((col) => col.name == snakeKey).firstOrNull;
      }
      
      if (column == null) {
         final camelKey = _toCamelCase(entry.key);
         column = columns.where((col) => col.name == camelKey).firstOrNull;
      }

      // Si no existe la columna en DB o es el ID (Identity), saltar
      if (column == null || column.isIdentity) continue;

      // 🚨 MODIFICACIÓN AQUÍ:
      // Solo saltamos campos de auditoría si NO estamos en la tabla Productos,
      // o mejor aún, dejamos que el Backend los maneje y los ignoramos siempre.
      final autoGeneratedFields = [
        'updated_at', 'deleted_at',
        'updatedat', 'deletedat',
      ];
      
      if (autoGeneratedFields.contains(column.name.toLowerCase())) continue;

      // Omitimos usuario_id aquí porque lo inyectaremos manualmente al final
      if (column.name.toLowerCase() == 'usuario_id') continue;

      // 2. Convertir el valor al tipo de dato correcto (String, int, double, etc.)
      final parsedValue = FieldTypeMapper.parseValue(column.type, entry.value);
      
      // 3. Traducir el nombre al formato que espera C# (PascalCase_con_Guion_Bajo)
      final backendName = _toBackendCase(column.name);
      
      preparedData[backendName] = parsedValue;
      print('   📤 Agregando: $backendName = $parsedValue');
    }

    // 🚨 INYECCIÓN AUTOMÁTICA DE USUARIO
    final hasUsuarioIdColumn = columns.any((c) => c.name.toLowerCase() == 'usuario_id');
    if (hasUsuarioIdColumn && currentUserId != null) {
       preparedData['UsuarioId'] = currentUserId;
       print('🔐 Auto-injectando UsuarioId: $currentUserId');
    }
    
    // 🚨 INYECCIÓN DE FECHA (Para evitar el error 500 en tablas como Productos)
    // Si la tabla tiene Created_At y no está en los datos, la agregamos
    final hasCreatedAt = columns.any((c) => c.name.toLowerCase() == 'created_at');
    if (hasCreatedAt && !preparedData.containsKey('Created_At')) {
      preparedData['Created_At'] = DateTime.now().toIso8601String();
      print('📅 Auto-injectando fecha de creación');
    }
    
    print('✅ Datos finales: $preparedData');
    return preparedData;
  }
}