import 'package:flutter/material.dart';
import '../../data/models/column_info_model.dart';
import '../../data/models/database_metadata_model.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_text_field.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_number_field.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_date_picker.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_checkbox.dart';
import '../../../../shared/widgets/dynamic_fields/dynamic_readonly_field.dart';
import '../../presentation/widgets/foreign_key_dropdown.dart';
import '../../../../core/network/column_name_mapper.dart';
import 'field_type_mapper.dart';

class FormGeneratorService {
  Widget generateField({
    required ColumnInfoModel column,
    required DatabaseMetadataModel metadata,
    required String currentDatabase,
    dynamic initialValue,
    required Function(String, dynamic) onChanged,
  }) {
    // print('🔨 generateField para columna: ${column.name}, initialValue: $initialValue');

    // 1. Identity / PK
    if (column.isIdentity) {
      if (initialValue != null) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: DynamicReadonlyField(
            label: column.name,
            value: initialValue.toString(),
          ),
        );
      }
      return const SizedBox.shrink();
    }

    // 2. Auto-generated fields
    final autoGeneratedFields = [
      'created_at', 'updated_at', 'deleted_at',
      'createdat', 'updatedat', 'deletedat',
    ];

    if (autoGeneratedFields.contains(column.name.toLowerCase())) {
      if (initialValue != null) {
        return Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: DynamicReadonlyField(
            label: column.name,
            value: initialValue.toString(),
          ),
        );
      }
      return const SizedBox.shrink(); 
    }

    // 3. Hide usuario_id
    if (column.name.toLowerCase() == 'usuario_id') {
      return const SizedBox.shrink();
    }

    // 4. FK Dropdown
    final fk = metadata.getForeignKeyForColumn(column.table, column.name);

    if (fk != null) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: ForeignKeyDropdown(
          label: column.name,
          databaseName: currentDatabase,
          referenceTable: fk.referenceTable,
          referenceColumn: fk.referenceColumn,
          isRequired: true, // SIEMPRE obligatorio
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    // 5. Data Types logic
    final type = column.type.toLowerCase();

    if (FieldTypeMapper.isStringType(type) || FieldTypeMapper.isTextType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicTextField(
          label: column.name,
          maxLength: column.maxLength,
          isRequired: true, //  SIEMPRE obligatorio
          initialValue: initialValue?.toString(),
          onChanged: (value) => onChanged(column.name, value),
          multiline: FieldTypeMapper.isTextType(type),
        ),
      );
    }

    if (FieldTypeMapper.isIntegerType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicNumberField(
          label: column.name,
          allowDecimal: false,
          isRequired: true, //  SIEMPRE obligatorio
          initialValue: initialValue?.toString(),
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isDecimalType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicNumberField(
          label: column.name,
          allowDecimal: true,
          isRequired: true, //  SIEMPRE obligatorio
          initialValue: initialValue?.toString(),
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isDateTimeType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicDatePicker(
          label: column.name,
          includeTime: type.contains('time') && type != 'time',
          isRequired: true, //  SIEMPRE obligatorio
          initialValue: initialValue,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    if (FieldTypeMapper.isBooleanType(type)) {
      return Padding(
        padding: const EdgeInsets.only(bottom: 16),
        child: DynamicCheckbox(
          label: column.name,
          initialValue: initialValue ?? false,
          onChanged: (value) => onChanged(column.name, value),
        ),
      );
    }

    // Default
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: DynamicTextField(
        label: column.name,
        isRequired: true, //  SIEMPRE obligatorio
        initialValue: initialValue?.toString(),
        onChanged: (value) => onChanged(column.name, value),
      ),
    );
  }

  /// BUSCADOR INTELIGENTE DE VALORES
  dynamic _getInitialValue(
    Map<String, dynamic>? initialData,
    String columnName,
    String tableName,
  ) {
    if (initialData == null || initialData.isEmpty) return null;

    // --- ZONA DE PARCHES (Casos Especiales) ---

    // 1. Estudiantes (Legajo -> Cedula)
    if (columnName.toLowerCase() == 'legajo') {
      if (initialData.containsKey('Cedula')) return initialData['Cedula'];
      if (initialData.containsKey('cedula')) return initialData['cedula'];
    }

    // 2. Búsqueda Fuzzy (Ignora mayúsculas y guiones bajos)
    // Resuelve: fecha_inscripcion vs FechaInscripcion
    final cleanColumnName = columnName.replaceAll('_', '').toLowerCase();
    
    for (var key in initialData.keys) {
      final cleanKey = key.replaceAll('_', '').toLowerCase();
      if (cleanKey == cleanColumnName) {
        return initialData[key];
      }
    }
    // --- FIN ZONA DE PARCHES ---

    // Búsquedas Estándar
    if (initialData.containsKey(columnName)) return initialData[columnName];

    final backendName = ColumnNameMapper.getBackendName(tableName, columnName);
    if (backendName != columnName && initialData.containsKey(backendName)) return initialData[backendName];

    final pascalCaseName = _toPascalCase(columnName);
    if (initialData.containsKey(pascalCaseName)) return initialData[pascalCaseName];

    final camelCaseName = _toCamelCase(columnName);
    if (initialData.containsKey(camelCaseName)) return initialData[camelCaseName];

    final lowerColumnName = columnName.toLowerCase();
    for (var entry in initialData.entries) {
      if (entry.key.toLowerCase() == lowerColumnName) return entry.value;
    }

    final snakeCaseName = _toSnakeCase(columnName);
    if (snakeCaseName != columnName && initialData.containsKey(snakeCaseName)) return initialData[snakeCaseName];

    return null;
  }

  List<Widget> generateForm({
    required String tableName,
    required DatabaseMetadataModel metadata,
    required String currentDatabase,
    Map<String, dynamic>? initialData,
    required Function(String, dynamic) onFieldChanged,
  }) {
    final columns = metadata.getColumnsForTable(tableName);

    return columns.map((column) {
      final initialValue = _getInitialValue(initialData, column.name, tableName);

      return generateField(
        column: column,
        metadata: metadata,
        currentDatabase: currentDatabase,
        initialValue: initialValue,
        onChanged: onFieldChanged,
      );
    }).toList();
  }

  String _toSnakeCase(String str) {
    return str.replaceAllMapped(
      RegExp(r'[A-Z]'),
      (match) => '_${match.group(0)!.toLowerCase()}',
    );
  }

  String _toCamelCase(String str) {
    return str.replaceAllMapped(
      RegExp(r'_([a-z])'),
      (match) => match.group(1)!.toUpperCase(),
    );
  }

  String _toPascalCase(String str) {
    final camel = _toCamelCase(str);
    if (camel.isEmpty) return camel;
    return camel[0].toUpperCase() + camel.substring(1);
  }
/// TRADUCTOR PARA ESCRITURA (Hacia el Backend)
String _toBackendCase(String str, String tableName) { 
  final String lowerStr = str.toLowerCase();

  // 🚨 REGLA PARA PROFESORES CORREGIDA
  if (tableName.toLowerCase() == 'profesores') {
    if (lowerStr == 'usuario_id') return 'usuarioId';
    if (lowerStr == 'email') return 'email';
    if (lowerStr == 'nombres') return 'nombres';
    if (lowerStr == 'especialidad') return 'especialidad';
  }

  if (lowerStr == 'id') return 'id';
  if (lowerStr == 'nombres' || lowerStr == 'nombre') return lowerStr;
    if (lowerStr == 'apellidos') return 'apellidos';
    if (lowerStr == 'activo') return 'activo';
    if (lowerStr == 'sku') return 'sku'; 
    if (lowerStr == 'descripcion') return 'descripcion'; 
    if (lowerStr == 'estado') return 'estado'; 
    if (lowerStr == 'especificaciones') return 'especificaciones'; 
    
    if (lowerStr == 'cedula' || lowerStr == 'legajo') return 'cedula';
    if (lowerStr == 'dni') return 'dni';

    final productosPascalGuion = [
      'precio_costo', 'precio_venta', 'categoria_id', 'proveedor_id'
    ];

    if (productosPascalGuion.contains(lowerStr)) {
      return str.split('_').map((part) {
        if (part.isEmpty) return '';
        return part[0].toUpperCase() + part.substring(1);
      }).join('_');
    }

    if (lowerStr == 'usuario_id') return 'usuario_Id';
    if (lowerStr == 'fecha_nacimiento') return 'fecha_Nacimiento';
    if (lowerStr == 'created_at') return 'created_At';

    if (lowerStr == 'genero') return 'genero';
    if (lowerStr == 'direccion') return 'direccion';
    if (lowerStr == 'telefono') return 'telefono';
    if (lowerStr == 'grupo_sanguineo') return 'grupo_Sanguineo';
    if (lowerStr == 'especialidad') return 'especialidad';
    if (lowerStr == 'consultorio') return 'consultorio';
    if (lowerStr == 'numero_licencia') return 'numero_Licencia';

    if (lowerStr == 'calificacion') return 'calificacion';

    final columnasInventarioGuion = [
      'estudiante_id', 'curso_id', 'fecha_inscripcion', 
      'cita_id', 'descripcion_diagnostico', 'tratamiento_recetado', 'proxima_visita',
      'producto_id', 'stock_actual', 'stock_minimo', 'ubicacion_almacen',
      'padre_id'
    ];

    if (columnasInventarioGuion.contains(lowerStr)) {
      return str.split('_').map((part) {
        if (part.isEmpty) return '';
        return part[0].toUpperCase() + part.substring(1);
      }).join('_');
    }

    final columnasSaludStrict = ['paciente_id', 'medico_id', 'fecha_hora', 'motivo_consulta'];
    if (columnasSaludStrict.contains(lowerStr)) return lowerStr;

    // Regla General: PascalCase simple
    return _toPascalCase(str);
  }

Map<String, dynamic> prepareDataForSubmit({
    required Map<String, dynamic> formData,
    required List<ColumnInfoModel> columns,
    required String tableName, 
    int? currentUserId,
    bool isEditing = false,
    int? existingId,       
  }) {
    final Map<String, dynamic> preparedData = {};

    print('🔍 Preparando datos para enviar:');

    preparedData['Id'] = isEditing ? existingId : 0;
    
    for (var entry in formData.entries) {
      ColumnInfoModel? column = columns.where((col) => col.name == entry.key).firstOrNull;

      if (column == null) {
        final snakeKey = _toSnakeCase(entry.key);
        column = columns.where((col) => col.name == snakeKey).firstOrNull;
      }
      
      if (column == null) {
          final camelKey = _toCamelCase(entry.key);
          column = columns.where((col) => col.name == camelKey).firstOrNull;
      }

      if (column == null || column.isIdentity || column.name.toLowerCase() == 'id') continue;

      final autoGeneratedFields = ['updated_at', 'deleted_at', 'updatedat', 'deletedat'];
      if (autoGeneratedFields.contains(column.name.toLowerCase())) continue;
      if (column.name.toLowerCase() == 'usuario_id') continue;

      final parsedValue = FieldTypeMapper.parseValue(column.type, entry.value);
      
      final backendName = _toBackendCase(column.name, tableName); 
      
      preparedData[backendName] = parsedValue;
      print('   📤 Agregando: $backendName = $parsedValue');
    }

    final hasUsuarioIdColumn = columns.any((c) => c.name.toLowerCase() == 'usuario_id');
    if (hasUsuarioIdColumn && currentUserId != null) {
       final userIdKey = _toBackendCase('usuario_id', tableName);
       preparedData[userIdKey] = currentUserId;
       print('🔐 Auto-injectando $userIdKey: $currentUserId');
    }
    
    final hasCreatedAt = columns.any((c) => c.name.toLowerCase() == 'created_at');
    if (hasCreatedAt && !preparedData.containsKey('CreatedAt')) {
      final createdAtKey = _toBackendCase('created_at', tableName);
      preparedData[createdAtKey] = DateTime.now().toIso8601String();
      print('📅 Auto-injectando $createdAtKey para C#');
    }
    
    print('✅ Datos finales preparados: $preparedData');
    return preparedData;
  }
}