// Mocks generated by Mockito 5.4.6 from annotations
// in herramienta_case/test/modules/auth/presentation/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:herramienta_case/modules/auth/data/datasources/auth_remote_datasource.dart'
    as _i2;
import 'package:herramienta_case/modules/auth/data/repositories/auth_repository.dart'
    as _i5;
import 'package:herramienta_case/modules/auth/domain/entities/user_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRemoteDataSource_0 extends _i1.SmartFake
    implements _i2.AuthRemoteDataSource {
  _FakeAuthRemoteDataSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_2 extends _i1.SmartFake implements _i4.UserEntity {
  _FakeUserEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRemoteDataSource get remoteDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteDataSource),
            returnValue: _FakeAuthRemoteDataSource_0(
              this,
              Invocation.getter(#remoteDataSource),
            ),
          )
          as _i2.AuthRemoteDataSource);

  @override
  _i3.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_1(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i3.SharedPreferences);

  @override
  _i6.Future<_i4.UserEntity> login({
    required String? username,
    required String? password,
    String? databaseName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
              #databaseName: databaseName,
            }),
            returnValue: _i6.Future<_i4.UserEntity>.value(
              _FakeUserEntity_2(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                  #databaseName: databaseName,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.UserEntity>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserEntity?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i6.Future<_i4.UserEntity?>.value(),
          )
          as _i6.Future<_i4.UserEntity?>);

  @override
  _i6.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
